06-Inventory.Api/WebInventory/ViewModels/Item.cs
using Microsoft.VisualBasic;

namespace WebInventory.ViewModels
{
    public class Item
    {
        public long Code { get; set; }
        public string Description { get; set; }

        public int Category { get; set; }
        public string CategoryDescription { get; set; }

        public string Brand { get; set; }
        public decimal Weight { get; set; }
        public string BarCode { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}

06-Inventory.Api/WebInventory/Pages/Items/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using System.Reflection.Metadata.Ecma335;
using System.Text.Encodings.Web;
using System.Text.Json;
using WebInventory.Helpers;
using WebInventory.Services.DTO;
using WebInventory.Services.Inventory;

namespace WebInventory.Pages.Items
{
    public class CreateModel : PageModel
    {
        public IHtmlLocalizer<Resources.SharedLabels> SharedLabelsLocalizer { get; private set; }
        public IHtmlLocalizer<Resources.SharedMessages> SharedMessagesLocalizer { get; private set; }
        public IHtmlLocalizer<Resources.SharedValidationMessages> SharedValidationMessagesLocalizer { get; private set; }
        public IHtmlLocalizer<EditModel> Localizer { get; private set; }
        private readonly IOptions<SettingsValue> _settings;
        private readonly IInventoryService _inventoryService;

        public string DataSource { get; set; }
        JsonSerializerOptions options = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };

        public string DataSourceCategories { get; set; }

        [BindProperty]
        public ViewModels.Item Item { get; set; }

        public CreateModel(IHtmlLocalizer<Resources.SharedLabels> sharedLabelsLocalizer,
                           IHtmlLocalizer<Resources.SharedMessages> sharedMessagesLocalizer,
                           IHtmlLocalizer<Resources.SharedValidationMessages> sharedValidationMessagesLocalizer,
                           IHtmlLocalizer<EditModel> localizer,
                           IOptions<SettingsValue> settings,
                           IInventoryService inventoryService)
        {
            SharedLabelsLocalizer = sharedLabelsLocalizer;
            SharedMessagesLocalizer = sharedMessagesLocalizer;
            SharedValidationMessagesLocalizer = sharedValidationMessagesLocalizer;
            Localizer = localizer;
            _settings = settings;
            _inventoryService = inventoryService;
        }

        public async Task<ActionResult> OnGet()
        {
            //if (string.IsNullOrEmpty(code) || code.Equals(nameof(code)))
            //    return RedirectToPage("./Index");

            await GetRequiredDataToLoadPage();
            return Page();

        }

        private async Task GetRequiredDataToLoadPage()
        {
            PageMessage msg;
            //ViewModels.Item item = new ViewModels.Item();
            try
            {
                var response = _inventoryService.GetAllCategories();

                await Task.WhenAll(response);

                DataSourceCategories = response.Result;
            }
            catch (Exception ex)
            {
                msg = new PageMessage(MessageType.Danger, SharedMessagesLocalizer.GetString("LoadingDataError", HtmlEncoder.Default.Encode(ex.Message)));
                TempData["PageMessage"] = JsonSerializer.Serialize(msg);
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            PageMessage msg = null;
            try
            {
                ItemsDTO item = new ItemsDTO();


                item = new ItemsDTO()
                {
                    Code = Item.Code,
                    Description = Item.Description,
                    Category = Item.Category,
                    Brand = Item.Brand,
                    Weight = Item.Weight,
                    BarCode = Item.BarCode,
                    UpdateDate = Item.UpdateDate
                };

                await _inventoryService.CreateItem(item);

                msg = new PageMessage(MessageType.Success, SharedMessagesLocalizer.GetString("EditSuccessMessage"));
                TempData["PageMessage"] = JsonSerializer.Serialize(msg);

                return RedirectToPage("./Index");
            }
            catch (Exception ex)
            {
                msg = new PageMessage(MessageType.Danger, SharedMessagesLocalizer.GetString("CreateErrorMessage", HtmlEncoder.Default.Encode(ex.Message)));
                TempData["PageMessage"] = JsonSerializer.Serialize(msg);
                return Page();
            }

            return RedirectToPage("./Index");
        }

        public string GetJSONViewModel()
        {
            //return JsonConvert.SerializeObject(Item);
            return JsonSerializer.Serialize(Item, options);
        }
    }
}

06-Inventory.Api/WebInventory/Pages/Items/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using System.Text.Encodings.Web;
using WebInventory.Helpers;
using WebInventory.Services.Inventory;

namespace WebInventory.Pages.Items
{
    public class DeleteModel : PageModel
    {

        public IHtmlLocalizer<Resources.SharedLabels> SharedLabelsLocalizer { get; private set; }
        public IHtmlLocalizer<Resources.SharedMessages> SharedMessagesLocalizer { get; private set; }
        private readonly IOptions<SettingsValue> _settings;
        private readonly IInventoryService _inventoryService;

        [BindProperty]
        public string Code { get; set; }


        public DeleteModel(IHtmlLocalizer<Resources.SharedLabels> sharedLabelsLocalizer,
                        IOptions<SettingsValue> settings,
                        IInventoryService inventoryService,
                        IHtmlLocalizer<Resources.SharedMessages> sharedMessagesLocalizer)
        {
            SharedLabelsLocalizer = sharedLabelsLocalizer;
            SharedMessagesLocalizer = sharedMessagesLocalizer;
            _settings = settings;
            _inventoryService = inventoryService;
        }

        public ActionResult OnGet(string code)
        {
            if (string.IsNullOrEmpty(code) || code.Equals(nameof(code)))
                return RedirectToPage("./Index");

            Code = code;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            PageMessage msg;
            try
            {
                if (string.IsNullOrEmpty(Code))
                {
                    msg = new PageMessage(MessageType.Danger, SharedMessagesLocalizer.GetString("NotFoundDeleteMessage"));
                    //TempData["PageMessage"] = JsonConvert.SerializeObject(msg);
                }
                else
                {
                    var response = await _inventoryService.DeleteItem(Convert.ToInt32(Code));

                    if (response.Type.Equals("Success"))
                    {

                        msg = new PageMessage(MessageType.Success, response.Message);

                        //TempData["PageMessage"] = JsonConvert.SerializeObject(msg);

                    }
                    else
                    {

                        //var resultMessage = JsonConvert.SerializeObject(new PageMessage(MessageType.Danger, response.Message));

                        //return new JsonResult(resultMessage);

                    };

                }

                return RedirectToPage("./Index");
            }
            catch (Exception ex)
            {
                msg = new PageMessage(MessageType.Danger, SharedMessagesLocalizer.GetString("DeleteErrorMessage", HtmlEncoder.Default.Encode(ex.Message)));
                //TempData["PageMessage"] = JsonConvert.SerializeObject(msg);
            }
            return Page();
        }
    }
}

06-Inventory.Api/WebInventory/Pages/Items/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;

namespace WebInventory.Pages.Items
{
    public class DetailsModel : PageModel
    {

        public IHtmlLocalizer<Resources.SharedLabels> SharedLabelsLocalizer { get; private set; }
        public IHtmlLocalizer<Resources.SharedMessages> SharedMessagesLocalizer { get; private set; }
        private readonly IOptions<SettingsValue> _settings;
        [BindProperty]
        public string Code { get; set; }


        public DetailsModel(IHtmlLocalizer<Resources.SharedLabels> sharedLabelsLocalizer,
                        IOptions<SettingsValue> settings,
                        IHtmlLocalizer<Resources.SharedMessages> sharedMessagesLocalizer)
        {
            SharedLabelsLocalizer = sharedLabelsLocalizer;
            SharedMessagesLocalizer = sharedMessagesLocalizer;
            _settings = settings;
        }

        public ActionResult OnGet(string code)
        {
            //PageMessage msg;
            //if (!base.ValidateFunctionalityAccessPolicy(SecurityConstants.FunctionalitiesConstants.General.Maintenances.MT_FORMS, SecurityConstants.ActionOptions.View))
            //{
            //    msg = new PageMessage(MessageType.Danger, SharedMessagesLocalizer.GetString("NoAccessFunctionality"));
            //    TempData["PageMessage"] = JsonConvert.SerializeObject(msg);

            //    return RedirectToPage("/_Error");
            //}

            if (string.IsNullOrEmpty(code) || code.Equals(nameof(code)))
                return RedirectToPage("./Index");

            Code = code;
            return Page();
        }

    }
}

06-Inventory.Api/WebInventory/Pages/Items/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using System.Reflection.Metadata.Ecma335;
using System.Text.Encodings.Web;
using System.Text.Json;
using WebInventory.Helpers;
using WebInventory.Services.DTO;
using WebInventory.Services.Inventory;

namespace WebInventory.Pages.Items
{
    public class EditModel : PageModel
    {
        public IHtmlLocalizer<Resources.SharedLabels> SharedLabelsLocalizer { get; private set; }
        public IHtmlLocalizer<Resources.SharedMessages> SharedMessagesLocalizer { get; private set; }
        public IHtmlLocalizer<Resources.SharedValidationMessages> SharedValidationMessagesLocalizer { get; private set; }
        public IHtmlLocalizer<EditModel> Localizer { get; private set; }
        private readonly IOptions<SettingsValue> _settings;
        private readonly IInventoryService _inventoryService;

        public string DataSource { get; set; }
        public string DataSourceCategories { get; set; }

        JsonSerializerOptions options = new JsonSerializerOptions() { PropertyNameCaseInsensitive = true };

        [BindProperty]
        public ViewModels.Item Item { get; set; }

        public EditModel(IHtmlLocalizer<Resources.SharedLabels> sharedLabelsLocalizer,
                           IHtmlLocalizer<Resources.SharedMessages> sharedMessagesLocalizer,
                           IHtmlLocalizer<Resources.SharedValidationMessages> sharedValidationMessagesLocalizer,
                           IHtmlLocalizer<EditModel> localizer,
                           IOptions<SettingsValue> settings,
                           IInventoryService inventoryService)
        {
            SharedLabelsLocalizer = sharedLabelsLocalizer;
            SharedMessagesLocalizer = sharedMessagesLocalizer;
            SharedValidationMessagesLocalizer = sharedValidationMessagesLocalizer;
            Localizer = localizer;
            _settings = settings;
            _inventoryService = inventoryService;
        }

        public async Task<IActionResult> OnGetAsync(string code)
        {
            if (string.IsNullOrEmpty(code) || code.Equals(nameof(code)))
                return RedirectToPage("./Index");

            await GetRequiredDataToLoadPage(code);
            return Page();

        }

        private async Task GetRequiredDataToLoadPage(string code)
        {
            PageMessage msg;
            //ViewModels.Item item = new ViewModels.Item();
            try
            {
                var response = _inventoryService.GetItem(Convert.ToInt32(code));
                var categories = _inventoryService.GetAllCategories();

                await Task.WhenAll(response, categories);


                Item = response.Result;
                DataSourceCategories = categories.Result;
            }
            catch (Exception ex)
            {
                msg = new PageMessage(MessageType.Danger, SharedMessagesLocalizer.GetString("LoadingDataError", HtmlEncoder.Default.Encode(ex.Message)));
                TempData["PageMessage"] = JsonSerializer.Serialize(msg);
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            PageMessage msg = null;
            try
            {
                ItemsDTO item = new ItemsDTO();


                item = new ItemsDTO()
                {
                    Code = Item.Code,
                    Description = Item.Description,
                    Category = Item.Category,
                    Brand = Item.Brand,
                    Weight = Item.Weight,
                    BarCode = Item.BarCode,
                    UpdateDate = Item.UpdateDate
                };

                await _inventoryService.SaveItem(item);

                msg = new PageMessage(MessageType.Success, SharedMessagesLocalizer.GetString("EditSuccessMessage"));
                TempData["PageMessage"] = JsonSerializer.Serialize(msg);

                return RedirectToPage("./Index");
            }
            catch (Exception ex)
            {
                msg = new PageMessage(MessageType.Danger, SharedMessagesLocalizer.GetString("CreateErrorMessage", HtmlEncoder.Default.Encode(ex.Message)));
                TempData["PageMessage"] = JsonSerializer.Serialize(msg);
                return Page();
            }

            return RedirectToPage("./Index");
        }

        public string GetJSONViewModel()
        {
            //return JsonConvert.SerializeObject(Item);
            return JsonSerializer.Serialize(Item, options);
        }
    }
}

06-Inventory.Api/WebInventory/ViewComponents/ItemDetailsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using WebInventory.Helpers;
using System.Text.Encodings.Web;
using System.Text.Json;
using WebInventory.Services.Inventory;

namespace WebInventory.ViewComponents
{
    public class ItemDetailsViewComponent : ViewComponent
    {
        private readonly IInventoryService _inventoryService;
        public IHtmlLocalizer<Resources.SharedMessages> SharedMessagesLocalizer { get; private set; }

        public ItemDetailsViewComponent(IHtmlLocalizer<Resources.SharedMessages> sharedMessagesLocalizer,
                                                   IInventoryService inventoryService)
        {
            _inventoryService = inventoryService;
            SharedMessagesLocalizer = sharedMessagesLocalizer;
        }

        public async Task<IViewComponentResult> InvokeAsync(string code)
        {
            PageMessage msg;
            ViewModels.Item item = new ViewModels.Item();
            try
            {
                var response = _inventoryService.GetItem(Convert.ToInt32(code));

                await Task.WhenAll(response);


                item = response.Result;
            }
            catch (Exception ex)
            {
                msg = new PageMessage(MessageType.Danger, SharedMessagesLocalizer.GetString("LoadingDataError", HtmlEncoder.Default.Encode(ex.Message)));
                TempData["PageMessage"] = JsonSerializer.Serialize(msg);
            }
            return View(item);
        }
    }
}

06-Inventory.Api/WebInventory/Pages/Items/Delete.cshtml
@page
@model WebInventory.Pages.Items.DeleteModel
@{
}
<!-- begin:: Content Head -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                @Model.SharedLabelsLocalizer["Maintenances"]
            </h3>
            <span class="kt-subheader__separator kt-hidden"></span>
            <div class="kt-subheader__breadcrumbs">
                <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                <a asp-page="Index" class="kt-subheader__breadcrumbs-link">
                    @Model.SharedLabelsLocalizer["Items"]
                </a>
                <span class="kt-subheader__breadcrumbs-separator"></span>
                <span class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--active">@Model.SharedLabelsLocalizer["FormDetail"]</span>
            </div>
        </div>
        <div class="kt-subheader__toolbar">
        </div>
    </div>
</div>
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-lg-12">

            <!--begin::Portlet-->
            <div class="kt-portlet">
                <form id="mainItemCode" class="kt-form kt-form--label-right" method="POST">
                    <div class="kt-portlet__body">
                        <div class="alert alert-warning fade show" role="alert">
                            <div class="alert-icon"><i class="flaticon-warning"></i></div>
                            <div class="alert-text">@Model.SharedMessagesLocalizer["DeleteConfirmation"]</div>
                        </div>
                        @await Component.InvokeAsync("ItemDetails", new { code = Model.Code })
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions">
                            <div class="row">
                                <div class="col-lg-12 text-right">
                                    <a asp-page="./Index" class="btn btn-mnt-secundary btn-elevate btn-elevate-air"><i class="fa fa-arrow-left"></i>@Model.SharedLabelsLocalizer["BackButton"]</a>
                                    <button type="button" id="deleteItem" class="btn btn-mnt-primary btn-elevate btn-elevate-air"><i class="fa fa-trash"></i>@Model.SharedLabelsLocalizer["DeleteButton"]</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!--end::Portlet-->

        </div>
    </div>
</div>

<!--begin::JS Code-->
@section Scripts{
    <script>

        function LoadControls() {
            LoadItemDetailsControls();
        }

        $('#deleteItem').click(function (e) {
            ShowDeleteConfirmationButtonMessage('mainItemCode');
        });
    </script>
}
<!--end::JS Code-->

06-Inventory.Api/WebInventory/Pages/Items/Details.cshtml
@page
@model WebInventory.Pages.Items.DetailsModel
@{
    ViewData["Title"] = "Detalle de un formulario";
}
<!-- begin:: Content Head -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                @Model.SharedLabelsLocalizer["Maintenances"]
            </h3>
            <span class="kt-subheader__separator kt-hidden"></span>
            <div class="kt-subheader__breadcrumbs">
                <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                <a asp-page="Index" class="kt-subheader__breadcrumbs-link">
                    @Model.SharedLabelsLocalizer["Items"]
                </a>
                <span class="kt-subheader__breadcrumbs-separator"></span>
                <span class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--active">@Model.SharedLabelsLocalizer["FormDetail"]</span>
            </div>
        </div>
        <div class="kt-subheader__toolbar">
        </div>
    </div>
</div>
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="row">
        <div class="col-lg-12">
            <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head ">
                    <div class="kt-portlet__head-label">
                        <h5 class="kt-portlet__head-title">
                            @Model.SharedLabelsLocalizer["FormDetail"]
                        </h5>
                    </div>
                </div>
                <div class="kt-portlet__body">

                    @await Component.InvokeAsync("ItemDetails", new { code = Model.Code })

                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <div class="row">
                            <div class="col-lg-12 text-right">
                                <a asp-page="./Index" class="btn btn-mnt-secundary btn-elevate btn-elevate-air"><i class="fa fa-arrow-left"></i>@Model.SharedLabelsLocalizer["BackButton"]</a>
                                <a asp-page="./Edit" asp-route-code="@Model.Code" class="btn btn-mnt-primary btn-elevate btn-elevate-air"><i class="fa fa-edit"></i>@Model.SharedLabelsLocalizer["EditButton"]</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--end::Portlet-->
        </div>
    </div>
</div>

<!--begin::JS Code-->
@section Scripts{
    <script>

        function LoadControls() {
            LoadItemDetailsControls();
        }
    </script>
}
<!--end::JS Code-->